# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1800, 450)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(150, 40, 260, 400))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(440, 40, 260, 400))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Button11_1 = QtWidgets.QPushButton(Form)
        self.Button11_1.setGeometry(QtCore.QRect(170, 80, 222, 34))
        self.Button11_1.setObjectName("Button11_1")
        self.Button11_2 = QtWidgets.QPushButton(Form)
        self.Button11_2.setGeometry(QtCore.QRect(170, 160, 222, 34))
        self.Button11_2.setObjectName("Button11_2")
        self.Button11_3 = QtWidgets.QPushButton(Form)
        self.Button11_3.setGeometry(QtCore.QRect(170, 240, 222, 34))
        self.Button11_3.setObjectName("Button11_3")
        self.Button11_4 = QtWidgets.QPushButton(Form)
        self.Button11_4.setGeometry(QtCore.QRect(170, 320, 222, 34))
        self.Button11_4.setObjectName("Button11_4")
        self.Button2_2 = QtWidgets.QPushButton(Form)
        self.Button2_2.setGeometry(QtCore.QRect(460, 200, 222, 34))
        self.Button2_2.setObjectName("Button2_2")
        self.Button2_3 = QtWidgets.QPushButton(Form)
        self.Button2_3.setGeometry(QtCore.QRect(460, 280, 222, 34))
        self.Button2_3.setObjectName("Button2_3")
        self.Button2_1 = QtWidgets.QPushButton(Form)
        self.Button2_1.setGeometry(QtCore.QRect(460, 120, 222, 34))
        self.Button2_1.setObjectName("Button2_1")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 80, 100, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 200, 100, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.load1 = QtWidgets.QLabel(Form)
        self.load1.setGeometry(QtCore.QRect(40, 140, 70, 20))
        self.load1.setObjectName("load1")
        self.load2 = QtWidgets.QLabel(Form)
        self.load2.setGeometry(QtCore.QRect(40, 260, 70, 20))
        self.load2.setObjectName("load2")
        self.label_image = QtWidgets.QLabel(Form)
        self.label_image.setGeometry(QtCore.QRect(830, 40, 400, 300))
        self.label_image.setObjectName("image")
        self.label_image2 = QtWidgets.QLabel(Form)
        self.label_image2.setGeometry(QtCore.QRect(1300, 40, 400, 300))
        self.label_image2.setObjectName("image2")
        

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Button11_1.setText(_translate("Form", "1.1 Color Seperate"))
        self.Button11_2.setText(_translate("Form", "1.2 Color Transform"))
        self.Button11_3.setText(_translate("Form", "1.3 Color Detection"))
        self.Button11_4.setText(_translate("Form", "1.4 Blending"))
        self.Button2_2.setText(_translate("Form", "2.2 Bilateral filter"))
        self.Button2_3.setText(_translate("Form", "2.3 Median filter"))
        self.Button2_1.setText(_translate("Form", "2.1 Gaussian blur"))
        self.pushButton.setText(_translate("Form", "Load Image 1"))
        self.pushButton_2.setText(_translate("Form", "Load Image 2"))
        self.load1.setText(_translate("Form", "image1"))
        self.load2.setText(_translate("Form", "image2"))
        self.groupBox.setTitle(_translate("Form", "1. Image Processing"))
        self.groupBox_2.setTitle(_translate("Form", "2. Image Smoothing"))
