# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.Button11_1 = QtWidgets.QPushButton(Form)
        self.Button11_1.setGeometry(QtCore.QRect(20, 160, 222, 34))
        self.Button11_1.setObjectName("Button11_1")
        self.Button11_2 = QtWidgets.QPushButton(Form)
        self.Button11_2.setGeometry(QtCore.QRect(20, 240, 222, 34))
        self.Button11_2.setObjectName("Button11_2")
        self.Button11_3 = QtWidgets.QPushButton(Form)
        self.Button11_3.setGeometry(QtCore.QRect(20, 320, 222, 34))
        self.Button11_3.setObjectName("Button11_3")
        self.Button11_4 = QtWidgets.QPushButton(Form)
        self.Button11_4.setGeometry(QtCore.QRect(20, 400, 222, 34))
        self.Button11_4.setObjectName("Button11_4")
        self.Button11_5 = QtWidgets.QPushButton(Form)
        self.Button11_5.setGeometry(QtCore.QRect(20, 480, 222, 34))
        self.Button11_5.setObjectName("Button11_4")

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 80, 222, 34))
        self.pushButton.setObjectName("pushButton")
        self.label_image = QtWidgets.QLabel(Form)
        self.label_image.setGeometry(QtCore.QRect(320, 80, 400, 300))
        self.label_image.setObjectName("image")
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Button11_1.setText(_translate("Form", "1. Show Train Images"))
        self.Button11_2.setText(_translate("Form", "2. Show Model Structure"))
        self.Button11_3.setText(_translate("Form", "3. Show Data Augmentation"))
        self.Button11_4.setText(_translate("Form", "4. Show Accuracy and Loss"))
        self.Button11_5.setText(_translate("Form", "5. Inference"))
        self.pushButton.setText(_translate("Form", "Load Image"))
